#### DATA PATHS
paths:

    out_folder : ''

    ######## TRAIN.PY NEEDED 
    out_model_name: '' 

    train_csv : './csv_full/flair-1-paths-train.csv'
    val_csv   : './csv_full/flair-1-paths-val.csv' 

    path_metadata_aerial: '../flair_aerial_metadata.json' 

    ######## PREDICT.PY NEEDED
    test_csv : './csv_full/flair-1-paths-test.csv' 
    ckpt_model_path: '' #'../checkpoints/ckpt-epoch=00-val_loss=0.86_baseline.ckpt'

    path_metadata_aerial: '../flair_aerial_metadata.json' 


#### USAGE
tasks:

    train: True
    predict: True # if tain = False, need for ckpt_model_path to be set  
    metrics: True

#### DATA CONF
num_classes: 13
channels: [1,2,3,4,5] # rasterio starts at 1
seed: 2022

#### NORMALIZATION
norm_type: scaling # [scaling, custom, without], default: scaling to range [0,1], see github readme
norm_means: [] # same length (order) as channels
norm_stds: [] # same length (order) as channels

#### TRAINING CONF
model_architecture: 'unet'
encoder_name: 'resnet34'

use_metadata: True
use_augmentation: True
use_weights: True
class_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0]

#### PREDICT CONF
georeferencing_output : True

#### HYPERPARAMETERS
batch_size: 5
learning_rate: 0.02
num_epochs: 1

#### COMPUTATIONAL RESSOURCES
accelerator: gpu 
num_nodes: 1
gpus_per_node: 1
strategy: 'auto' 
num_workers: 10

#### PRINT/LOG
copy_csv_to_output: True
enable_progress_bar: True
progress_rate: 10
