#### DATA PATHS
data:

  path_aerial_train: ""  #e.g.,  ./flair_aerial_train or toy
  path_aerial_test:  ""  #e.g., ./flair_1_aerial_test or toy
  
  path_labels_train: ""  #e.g., ./flair_labels_train or toy
  path_labels_test:  "" #e.g.,  ./flair_1_labels_test or toy

  path_metadata_aerial: "" #e.g., ./flair-1_metadata_aerial.json
  
  
outputs:

  out_folder: "" 
  out_model_name: ""


num_classes: 13

#### TRAINING CONF
use_weights: True
class_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0]
use_metadata: False
use_augmentation: False


#### HYPERPARAMETERS
batch_size: 2
learning_rate: 0.02
num_epochs: 3

#### COMPUTATIONAL
accelerator: gpu
num_nodes: 1
gpus_per_node: 1
strategy: null # null if only one GPU, else 'ddp' 
num_workers: 1

#### PRINT
enable_progress_bar: True
progress_rate: 10

