#### DATA PATHS
paths:

    out_folder : ''

    ######## TRAIN.PY NEEDED 
    out_model_name: '' 

    train_csv : './csv_full/flair-1-paths-train.csv' # path to .csv containing paths to IMG/MSK pairs
    val_csv   : './csv_full/flair-1-paths-val.csv' # path to .csv containing paths to IMG/MSK pairs

    path_metadata_aerial: '../flair_aerial_metadata.json' # path to aerial images metadata file

    ######## PREDICT.PY NEEDED
    test_csv : './csv_full/flair-1-paths-test.csv' # path to .csv containing paths to IMG/MSK pairs
    ckpt_model_path: '../checkpoints/ckpt-epoch=00-val_loss=0.86_finished_full.ckpt' # path to .ckpt model

    path_metadata_aerial: '../flair_aerial_metadata.json' # path to aerial images metadata file



#### USAGE
tasks:

    train: True
    predict: True # if tain = False, need for ckpt_model_path to be set  
    metrics: True



num_classes: 13
num_channels: 5
seed: 2022

#### TRAINING CONF
model_architecture: 'unet'
encoder_name: 'resnet34'

use_metadata: True
use_augmentation: True
use_weights: True
class_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0]

#### PREDICT CONF
metrics : True 
georeferencing_output : True
num_classes: 13

#### HYPERPARAMETERS
batch_size: 5
learning_rate: 0.02
num_epochs: 1

#### COMPUTATIONAL RESSOURCES
accelerator: gpu # or cpu
num_nodes: 1
gpus_per_node: 1
strategy: 'auto' # null if only one GPU, else 'ddp' 
num_workers: 10

#### PRINT PROGRESS
enable_progress_bar: True
progress_rate: 10
